### ISSUE TITLE
Stars should be created/destroyed via AJAX

### ISSUE THREAD

**Issue by alexkahn** [alexkahn/reservator#5]
In app/assets/javascripts/star.js.coffee, something like:

```
function toggleStar ->
var url;
if $('#star').hasClass('starred') 
   url = '/stars/delete'
else 
  url = 'stars/create'

$.post({
  url: url,
  method: "post",
  success: ->
    $('#star').toggle( '.starred')
})
```

If erb can be used to pass in the url or other fun stuff then a more complicated method may not be needed.

There should of course be routes that `responds_to` json and render json response objects that confirm or deny the creation of the star.

**Comment by alexkahn** [comment]
In the process of doing this, I'm getting stuck with the following:

```
Started GET "/restaurant/241/star" for 127.0.0.1 at 2014-12-07 11:49:55 -0600

ActionController::RoutingError (No route matches [GET] "/restaurant/241/star"):
  actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.6) lib/rails/engine.rb:514:in `call'
  railties (4.1.6) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
  /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'


  Rendered /usr/lib/ruby/gems/1.9.1/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.8ms)
  Rendered /usr/lib/ruby/gems/1.9.1/gems/actionpack-4.1.6/lib/action_dispatch/middleware/templates/rescues/routing_error.text.erb (6.8ms)
```

Clearly the link is pointing to a GET but the [JS handler](https://github.com/alexkahn/reservator/blob/starAjax/app/assets/javascripts/star.js.coffee) should be intercepting the event, preventing it from performing the GET.

In addition, the [link](https://github.com/alexkahn/reservator/blob/starAjax/app/views/restaurant/show.html.erb#L30) itself doesn't seem right. In the routes, the path is named as the `restaurant_star_index` that gets the restaurant id as a param but is in fact the create path.

Help me @carolineartz, you're my only hope!

**Comment by carolineartz** [comment]
@alexkahn the first issue I see is that your route resources should be plural

**Comment by alexkahn** [comment]
Can you link the [line](https://github.com/alexkahn/reservator/blob/master/config/routes.rb)?

**Comment by carolineartz** [comment]
sure, yeah i'm writing up some notes on a few things right now

**Comment by alexkahn** [comment]
Sweet! Thanks so much!

**Comment by carolineartz** [comment]
ok so before we consider the ajax and other things, all your resources need to be plural: your `resources :reservation` => `resources :reservations`, your `resources :star` => `resources :stars`, etc, those, restaurants, categories, etc.

also, concerns aren't necessary at this point, you don't reuse that code anywhere. concerns function to declare common routes that can be reused inside other resources and routes. You don't use star or reservation resources anywhere but restaurants

``` ruby
concern :commentable do
  resources :comments
end

resources :messages, concerns: :commentable
resources :posts, concerns: :commentable
```

is the same as

``` ruby
resources :messages do
  resources :comments
end

resources :posts do
  resources :comments
end
``
```

**Comment by alexkahn** [comment]
Routes ammended with https://github.com/alexkahn/reservator/commit/86a1279b8826e75c25577a9c23cf5da493d7c01a

**Comment by carolineartz** [comment]
awesome--ok, i'm on a phone call about a job :) but i'll have some time after. you watched this https://gorails.com/episodes/jquery-ujs-and-ajax ? 

and you still need to update the last block, categories and restaurants.

**Comment by alexkahn** [comment]
Last block fixed with: https://github.com/alexkahn/reservator/commit/e07aa2f112ef5b54f2ef954c9f26918625892ea0

**Comment by alexkahn** [comment]
Fixed
